name: Component - Build Frontend
on:
  workflow_call:
    inputs:
      build_type:
        required: true
        type: string
      # publish_location is not used for the build itself, but is needed
      # to set the concurrency group so that concurrent builds for the
      # same environment (dev/prod) cancel each other.
      publish_location:
        required: true
        type: string
      git_ref:
        required: false
        type: string
        default: ''
      add_robots_txt:
        required: false
        type: boolean
        default: false
      artifact_name:
        required: true
        type: string
    secrets:
      strapi_token:
        required: true
      strapi_api_url:
        required: true
      host_server:
        required: true

jobs:
  build-site:
    runs-on: ubuntu-latest
    concurrency:
      group: build-${{ inputs.publish_location }}
      cancel-in-progress: true
    steps:
      - name: git checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.git_ref }}
      - name: Build Gatsby
        run: |
          cd ${{ github.workspace }}/frontend

          # Add env file
          echo 'STRAPI_TOKEN=${{ secrets.strapi_token }}' > ./.env.${{ inputs.build_type }}
          echo 'STRAPI_API_URL=${{ secrets.strapi_api_url }}' >> ./.env.${{ inputs.build_type }}

          npm install
          NODE_ENV=${{ inputs.build_type }} HOST_ORIGIN=${{ secrets.host_server }} npm run build
      - name: Add anti-webscraping
        if: ${{ inputs.add_robots_txt }}
        run: |
          echo 'User-agent: *' > ./frontend/public/robots.txt
          echo 'Disallow: /' >> ./frontend/public/robots.txt
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: ./frontend/public/
          retention-days: 1
